name: HostKeep Property Portfolio
favicon: null
layout_spectrum: 0.032735679065808654
typography_spectrum: 0.20601067994721234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3496809443458915
  lightness: 0.6141708998475224
  saturation: 0.5138608037959784
  rhythmicContrast: 0.9742726285476238
purpose: []
